---
server:  port: 8888

spring:
#  profiles:
#    active: composite
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/justin-tuck/spring-cloudconfig-dc-tolls
          uri: https://github.com/harishThadka/springcloud-config
